apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: testaks.azurecr.io/api
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: MONGO_DB_HOST
          value: db
