#!/bin/sh

R_GRP=todo
CLSTR=todo

# Enable AKS preview
echo Signing up for AKS preview
# az provider register -n Microsoft.Network
# az provider register -n Microsoft.Storage
# az provider register -n Microsoft.Compute
# az provider register -n Microsoft.ContainerService

# Create Azure Resource Group
echo Create Azure Resource Group - $R_GRP
az group create --name $R_GRP --location centralus

# Create AKS Cluster on Resource Group
az aks create --resource-group $R_GRP --name $CLSTR --node-count 1 --generate-ssh-keys

# Connect to AKS Cluster
az aks get-credentials --resource-group $R_GRP --name $CLSTR
