apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: testaks.azurecr.io/app
        ports:
        - containerPort: 80
